1.Implemente un algoritmo de multiplicación de matrices en tiempo O(n^3) que calcule cada elemento de la matriz C como c_{ij} = \sum_{k=1}^n a_{ik}*b_{kj}


In [1]:
import math
import numpy as np
import pylab as pl
%matplotlib inline

In [3]:
class Counter:
    '''
    Class Counter
    Implements a step counter, which is used to compute the number of basic operations performed in
    a particular call to a function.
    '''
    def __init__(self):
        self.steps = 0

    def reset(self):
        self.steps = 0

    def count(self):
        self.steps += 1

    def print_steps(self):
        print "Number of steps =", self.steps



def mult1(m_1,m_2, p):
    m = np.zeros((p,p))
    for i in range(p):
        for j in range(p):
            for k in range(p):
                m[i][j] = m[i][j] + (m_1[i][k]*m_2[k][j])
    return m

In [4]:
x =4
mat = np.random.randint(0,20,(x,x))
matr = np.random.randint(0,20,(x,x))
mult1(mat,matr,x)

array([[ 173.,  219.,  246.,  380.],
       [  46.,   72.,   57.,  101.],
       [ 207.,  230.,   87.,  216.],
       [ 353.,  348.,  240.,  331.]])

2.Implemente un algoritmo de multiplicación de matrices basado en una estrategía de multiplicación de matrices en tiempo O(n^3) donde cada matriz es dividida en 4 partes iguales.

In [8]:
def sum(m,n):
    t = len(m)
    r = np.zeros((len(m),len(n)))
    for i in range(t):
        for j in range(t):
            r[i][j] = m[i][j] + n[i][j]
    return r
def mxm(m,n): 
    results = np.zeros((len(m),len(n)))
    for i in range(len(m)):
           for j in range(len(n[0])):
                   for k in range(len(n)):
                           results[i][j] += m[i][k] * n[k][j]
    return results
def mat_MDC(m, n):
    flag=0 
    if (len(m) <= 2):
         return mxm(m,n)
    else :
        L=len(m)
        if(L%2!=0):
            x1 = np.zeros((L, 1))
            y1 = np.zeros((1, L+1))
            m1 = np.c_[m1,x1]
            m1 = np.r_[m1,y1]
            n1 = np.c_[n1,x1]
            n1 = np.r_[n1,y1]
            L=L+1    
            flag=1 
        L= (L)/2
        a1=m1[:L,:L]
        b1=m1[:L,L:]
        c1=m1[L:,:L]
        d1=m1[L:,L:]
        b2=n[:L,:L]
        b3=n[:L,L:]
        b4=n[L:,:L]
        b5=n[L:,L:]     
    a =mat_MDC(a1,b2)
    b =mat_MDC(b1,b4)
    c =mat_MDC(a1,b3)
    d =mat_MDC(a1,b5)
    e=mat_MDC(c1,b2)
    f =mat_MDC(d1,b4)
    g =mat_MDC(c1,b3)
    h =mat_MDC(d1,b5)
    aa = sum(a,b)
    bb = sum(c,d)
    cc = sum(e,f)
    dd = sum(g,h)
    aa = np.c_[aa,bb]
    cc = np.c_[cc,dd]
    aa = np.r_[aa,cc]
    if flag==1:
        l=len(aa)
        aa = aa[:l-1,:l-1]
    return aa

In [12]:
m= np.random.randint(15, size=(4,4)) 
n= np.random.randint(15, size=(4,4)) 

print mxm(m,n)
print 

[[ 319.  236.  180.   66.]
 [ 151.  225.  152.   64.]
 [ 165.  213.  111.   64.]
 [ 196.  297.  146.   90.]]



Implemente el algoritmo de strassen

In [24]:
from optparse import OptionParser
from math import ceil, log




def strassenR(A, B):
    
    n = len(A)

    if n <= LEAF_SIZE:
        return ikjMatrixProduct(A, B)
    else:
        
        newSize = n/2
        a11 = [[0 for j in xrange(0, newSize)] for i in xrange(0, newSize)]
        a12 = [[0 for j in xrange(0, newSize)] for i in xrange(0, newSize)]
        a21 = [[0 for j in xrange(0, newSize)] for i in xrange(0, newSize)]
        a22 = [[0 for j in xrange(0, newSize)] for i in xrange(0, newSize)]

        b11 = [[0 for j in xrange(0, newSize)] for i in xrange(0, newSize)]
        b12 = [[0 for j in xrange(0, newSize)] for i in xrange(0, newSize)]
        b21 = [[0 for j in xrange(0, newSize)] for i in xrange(0, newSize)]
        b22 = [[0 for j in xrange(0, newSize)] for i in xrange(0, newSize)]

        aResult = [[0 for j in xrange(0, newSize)] for i in xrange(0, newSize)]
        bResult = [[0 for j in xrange(0, newSize)] for i in xrange(0, newSize)]

       
        for i in xrange(0, newSize):
            for j in xrange(0, newSize):
                a11[i][j] = A[i][j]            
                a12[i][j] = A[i][j + newSize]    
                a21[i][j] = A[i + newSize][j]    
                a22[i][j] = A[i + newSize][j + newSize] 

                b11[i][j] = B[i][j]            
                b12[i][j] = B[i][j + newSize]   
                b21[i][j] = B[i + newSize][j]    
                b22[i][j] = B[i + newSize][j + newSize] 

        
        aResult = add(a11, a22)
        bResult = add(b11, b22)
        p1 = strassenR(aResult, bResult) 

        aResult = add(a21, a22)      
        p2 = strassenR(aResult, b11)  

        bResult = subtract(b12, b22) 
        p3 = strassenR(a11, bResult) 

        bResult = subtract(b21, b11) 
        p4 =strassenR(a22, bResult)   

        aResult = add(a11, a12)     
        p5 = strassenR(aResult, b22)    

        aResult = subtract(a21, a11) 
        bResult = add(b11, b12)     
        p6 = strassenR(aResult, bResult) 

        aResult = subtract(a12, a22) 
        bResult = add(b21, b22)      
        p7 = strassenR(aResult, bResult) 

        c12 = add(p3, p5)
        c21 = add(p2, p4)  

        aResult = add(p1, p4) 
        bResult = add(aResult, p7) 
        c11 = subtract(bResult, p5) 

        aResult = add(p1, p3)
        bResult = add(aResult, p6) 
        c22 = subtract(bResult, p2) 

      
        C = [[0 for j in xrange(0, n)] for i in xrange(0, n)]
        for i in xrange(0, newSize):
            for j in xrange(0, newSize):
                C[i][j] = c11[i][j]
                C[i][j + newSize] = c12[i][j]
                C[i + newSize][j] = c21[i][j]
                C[i + newSize][j + newSize] = c22[i][j]
        return C

if __name__ == "__main__":
    parser = OptionParser()
    parser.add_option("-i", dest="filename", default="2000.in",
         help="input file with two matrices", metavar="FILE")
    parser.add_option("-l", dest="LEAF_SIZE", default="8",
         help="when do you start using ikj", metavar="LEAF_SIZE")
    (options, args) = parser.parse_args()

    LEAF_SIZE = options.LEAF_SIZE
    A, B = read(options.filename)
# tomado de https://martin-thoma.com/strassen-algorithm-in-python-java-cpp/#python

Usage: __main__.py [options]

__main__.py: error: no such option: -f


SystemExit: 2

In [26]:
A = np.random.randint(10, size=(3, 3))
B = np.random.randint(10, size=(3, 3))

C = strassenR(A,B)

NameError: global name 'LEAF_SIZE' is not defined